#!/bin/bash

function fatal()
{
    echo "Error: $*"
    exit 1
}

dir=$1

# Check the commandline options
if [ -z "$dir" ] ; then
    echo "Usage: fw-clean <firmware directory>"
    exit 2
fi

# Check the user
if [ $(whoami) != 'root' ] ; then
    fatal "You need to be root to run this script"
fi

if [ -d $dir ] ; then
    sync
    umount $dir/ramdisk_el.d 2> /dev/null
    rm -rf $dir || fatal "Failed to remove $dir"
fi
